---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Pull Image
      shell: docker pull shouryap1/calculator:latest

    - name: Run the container
      shell: docker create -it --name Calculator shouryap1/calculator

    - name: Run
      shell: docker start -a -i Calculator